spring.application.name=demo
spring.application.name=SpringBootSecurityPostgresqlApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/user_api?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=lalosanch06
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
